# Generated by Django 4.2.2 on 2023-07-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        
    ]
