# Generated by Django 4.2.2 on 2023-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_create_courses_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edited')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('sname', models.CharField(max_length=256, verbose_name='Surname')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('course', models.ManyToManyField(to='mainapp.courses')),
            ],
        ),
    ]
