# Generated by Django 4.2.2 on 2023-07-11 19:18

from django.db import migrations
from django.core.management import call_command

def forwards_func(apps, schema_editor):
    call_command("loaddata", "lessons")


def reverse_func(apps, schema_editor):
    News = apps.get_model("mainapp", "Lessons")
    News.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_load_teachers_data'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
    
