# Generated by Django 4.2.2 on 2023-07-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_load_lessons_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
