# Generated by Django 4.2.2 on 2023-07-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=256, verbose_name='email address'),
        ),
    ]
