# Generated by Django 4.2.2 on 2023-07-13 11:58

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='lower_user_name_unique'),
        ),
    ]
